# Generated by Django 3.2.9 on 2021-11-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FilePathField(default='https://packed.co/images/home/group-holidays-handled.jpg', path='/img'),
            preserve_default=False,
        ),
    ]
